import { Octokit } from '@octokit/rest';
import { loadConfig } from './config';
import { CrashAnalysis } from '../types';

function getOctokit(): Octokit {
  const config = loadConfig();
  return new Octokit({ auth: config.github.token });
}

export async function createPullRequest(params: {
  branch: string;
  baseBranch: string;
  crashSubject: string;
  analysis: CrashAnalysis;
}): Promise<string> {
  const config = loadConfig();
  const octokit = getOctokit();

  const body = `## Crash Report Auto-Fix

### Exception
- **Type**: ${params.analysis.exceptionType}

### Root Cause
${params.analysis.rootCause}

### Fix Description
${params.analysis.suggestedFix}

### Changed Files
${params.analysis.fixedFiles.map((f) => `- \`${f.path}\``).join('\n')}

### Diff
\`\`\`diff
${params.analysis.fixedFiles.map((f) => f.diff).join('\n\n')}
\`\`\`

---
> Auto-generated by **CrashPilot** using Claude AI analysis
`;

  const pr = await octokit.pulls.create({
    owner: config.github.owner,
    repo: config.github.repo,
    title: `[CrashPilot] Fix: ${params.crashSubject}`,
    body,
    head: params.branch,
    base: params.baseBranch,
  });

  return pr.data.html_url;
}
