import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { Octokit } from '@octokit/rest';
import { loadConfig } from './config';
import { CrashAnalysis } from '../types';

function getOctokit(): Octokit {
  const config = loadConfig();
  return new Octokit({ auth: config.github.token });
}

/** Parse { owner, repo } from a GitHub remote URL (https or ssh). */
function parseGitHubOwnerRepo(url: string): { owner: string; repo: string } | null {
  const m = url.match(/github\.com[:/]([^/]+)\/([^/.]+)/);
  if (!m) return null;
  return { owner: m[1], repo: m[2].replace(/\.git$/, '') };
}

/** True if ref looks like a tag (e.g. "pos/2.2.1/29" — 3 segments, last numeric). */
function isTagRef(ref: string): boolean {
  const parts = ref.split('/');
  return parts.length >= 3 && /^\d+$/.test(parts[parts.length - 1]);
}

/** Get the default branch of a GitHub repo via API. */
async function getDefaultBranch(octokit: Octokit, owner: string, repo: string): Promise<string> {
  try {
    const { data } = await octokit.repos.get({ owner, repo });
    return data.default_branch;
  } catch {
    return 'master';
  }
}

/** Read submodule paths from .gitmodules (handles CRLF). */
function readSubmodulePaths(repoDir: string): string[] {
  const file = path.join(repoDir, '.gitmodules');
  if (!fs.existsSync(file)) return [];
  const paths: string[] = [];
  for (const line of fs.readFileSync(file, 'utf-8').split('\n')) {
    const m = line.match(/^\s*path\s*=\s*(.+?)[\r\s]*$/);
    if (m) paths.push(m[1].trim());
  }
  return paths;
}

/** Get the remote origin URL of a git repo / submodule directory. */
function getRemoteUrl(dir: string): string | null {
  try {
    return execSync('git remote get-url origin', { cwd: dir, encoding: 'utf-8' }).trim();
  } catch {
    return null;
  }
}

export async function createPullRequest(params: {
  branch: string;
  baseBranch: string;
  crashSubject: string;
  analysis: CrashAnalysis;
  repoDir?: string;
}): Promise<string> {
  const config = loadConfig();
  const octokit = getOctokit();

  const body = `## Crash Report Auto-Fix

### Exception
- **Type**: ${params.analysis.exceptionType}

### Root Cause
${params.analysis.rootCause}

### Fix Description
${params.analysis.suggestedFix}

### Changed Files
${params.analysis.fixedFiles.map((f) => `- \`${f.path}\``).join('\n')}

### Diff
\`\`\`diff
${params.analysis.fixedFiles.map((f) => f.diff).join('\n\n')}
\`\`\`

---
> Auto-generated by **CrashPilot** using Claude AI analysis
`;

  const prUrls: string[] = [];

  // ── Collect repos that need PRs ─────────────────────────────────────────
  // Each entry: { owner, repo, repoDir, isSubmodule }
  const targets: { owner: string; repo: string; dir: string }[] = [];

  // Parent repo: derive owner/repo from config or repoUrl
  const parentUrl = config.git.repoUrl || '';
  const parentParsed = (config.github.owner && config.github.repo)
    ? { owner: config.github.owner, repo: config.github.repo }
    : parseGitHubOwnerRepo(parentUrl);

  if (parentParsed) {
    targets.push({ ...parentParsed, dir: params.repoDir || '' });
  }

  // Submodule repos: find submodules that contain changed files
  if (params.repoDir) {
    const submodulePaths = readSubmodulePaths(params.repoDir);
    const changedSubmodules = new Set<string>();
    for (const f of params.analysis.fixedFiles) {
      const norm = f.path.replace(/\\/g, '/');
      for (const sub of submodulePaths) {
        if (norm.startsWith(sub + '/') || norm === sub) {
          changedSubmodules.add(sub);
        }
      }
    }
    for (const sub of changedSubmodules) {
      const subDir = path.join(params.repoDir, sub);
      const subUrl = getRemoteUrl(subDir);
      if (!subUrl) continue;
      const parsed = parseGitHubOwnerRepo(subUrl);
      if (parsed) targets.push({ ...parsed, dir: subDir });
    }
  }

  // ── Create a PR for each target repo ────────────────────────────────────
  for (const target of targets) {
    let base = params.baseBranch;
    if (isTagRef(base)) {
      // Tags can't be PR bases — use the repo's default branch
      base = await getDefaultBranch(octokit, target.owner, target.repo);
    }

    try {
      const pr = await octokit.pulls.create({
        owner: target.owner,
        repo: target.repo,
        title: `[CrashPilot] Fix: ${params.crashSubject}`,
        body,
        head: params.branch,
        base,
      });
      prUrls.push(pr.data.html_url);
    } catch (err: any) {
      // Don't fail the whole step if one PR creation fails — log and continue
      prUrls.push(`ERROR creating PR for ${target.owner}/${target.repo}: ${err.message}`);
    }
  }

  if (prUrls.length === 0) throw new Error('No GitHub repos could be determined for PR creation.');
  return prUrls.join('\n');
}
